# Generated by Django 5.2.11 on 2026-03-03 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorization', '0003_cesfam_city_cesfam_region'),
        ('social_recipe', '0002_paciente_email_paciente_latitude_paciente_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectorization.sectorterritorial'),
        ),
    ]
