# Generated by Django 5.2.11 on 2026-03-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_recipe', '0003_alter_paciente_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sector',
        ),
    ]
