# Generated by Django 5.2.11 on 2026-03-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_recipe', '0004_remove_paciente_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
