# Generated by Django 5.0.7 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creater_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
