# Generated by Django 5.2.11 on 2026-03-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorization', '0001_initial'),
        ('users', '0003_usuario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cesfam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='sectorization.cesfam'),
        ),
    ]
