# Generated by Django 5.2.11 on 2026-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_cesfam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='region',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PROF', 'Profesional')], max_length=15),
        ),
    ]
