# Generated by Django 5.2.11 on 2026-03-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorization', '0003_cesfam_city_cesfam_region'),
        ('users', '0005_remove_usuario_address_remove_usuario_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='city',
            field=models.CharField(default='Villa Alemana', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cesfam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='sectorization.cesfam'),
        ),
    ]
