# Generated by Django 5.2.11 on 2026-03-03 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorization', '0003_cesfam_city_cesfam_region'),
        ('users', '0006_usuario_city_alter_usuario_cesfam'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectorization.sectorterritorial'),
        ),
    ]
