# Generated by Django 5.2.11 on 2026-03-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cesfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_deis', models.CharField(blank=True, help_text='Código único del centro', max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectorTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('poblacion', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('geojson_data', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cesfam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='sectorization.cesfam')),
            ],
        ),
    ]
