# Generated by Django 5.2.11 on 2026-03-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectorization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorterritorial',
            old_name='geojson_data',
            new_name='geojson',
        ),
    ]
