# Generated by Django 5.2.11 on 2026-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectorization', '0002_rename_geojson_data_sectorterritorial_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesfam',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cesfam',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
