# Generated by Django 5.0.7 on 2026-02-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_activo', models.CharField(blank=True, choices=[('espacio_publico', 'Espacio Público / Área Verde'), ('organizacion_social', 'Organización Social'), ('establecimiento_salud', 'Establecimiento de Salud'), ('establecimiento_educacional', 'Establecimiento Educacional'), ('organizacion_deportiva', 'Club Deportivo'), ('grupo_apoyo', 'Grupo de Apoyo'), ('programa_municipal', 'Programa Municipal'), ('centro_cultural', 'Centro Cultural / Biblioteca'), ('organizacion_adulto_mayor', 'Organización Adulto Mayor'), ('organizacion_juvenil', 'Organización Juvenil'), ('red_vecinal', 'Junta de Vecinos'), ('otro', 'Otro')], max_length=50, null=True)),
                ('categoria_mais', models.CharField(blank=True, choices=[('promocion', 'Promoción de la Salud'), ('prevencion', 'Prevención de Enfermedades'), ('recuperacion', 'Recuperación y Rehabilitación'), ('participacion', 'Participación Social')], max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('horario', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_info', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('revisado_mais', models.BooleanField(default=False)),
            ],
        ),
    ]
