# Generated by Django 5.0.7 on 2026-02-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunity_assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivoComunitario',
            new_name='ComunityAsset',
        ),
    ]
