# Generated by Django 5.0.7 on 2026-02-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity_assets', '0002_rename_activocomunitario_comunityasset'),
        ('users', '0002_usuario_creater_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunityasset',
            name='revisado_mais',
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='aceptado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_validado', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activo_propuesto', to='users.usuario'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado / Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
