# Generated by Django 5.0.7 on 2026-02-15 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity_assets', '0003_remove_comunityasset_revisado_mais_and_more'),
        ('users', '0002_usuario_creater_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunityasset',
            name='aceptado_por',
        ),
        migrations.AlterField(
            model_name='comunityasset',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to='users.usuario'),
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado / Validado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Motivo del rechazo o notas de la validación', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='comunity_assets.comunityasset')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_validación', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Historial de Activo',
                'verbose_name_plural': 'Historiales de Activos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
