# Generated by Django 5.0.7 on 2026-02-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity_assets', '0004_remove_comunityasset_aceptado_por_and_more'),
        ('users', '0002_usuario_creater_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assethistory',
            options={'ordering': ['-fecha_movimiento']},
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='aceptado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_validados', to='users.usuario'),
        ),
    ]
