# Generated by Django 5.0.7 on 2026-02-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity_assets', '0005_alter_assethistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunityasset',
            name='poblacion_objetivo',
            field=models.CharField(choices=[('general', 'Público General'), ('ninos', 'Niños y Adolescentes'), ('adulto_mayor', 'Personas Mayores'), ('mujeres', 'Mujeres / Gestantes'), ('migrantes', 'Población Migrante'), ('discapacidad', 'Personas con Discapacidad')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='requiere_inscripcion',
            field=models.BooleanField(default=False, help_text='¿Requiere estar inscrito en el CESFAM o registro previo?'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='tipo_financiamiento',
            field=models.CharField(choices=[('gratuito', 'Gratuito / Público'), ('copago', 'Copago / Fonasa'), ('pago', 'Privado / De Pago'), ('donacion', 'Aporte Voluntario / Donación')], default='gratuito', max_length=20),
        ),
    ]
