# Generated by Django 5.0.7 on 2026-02-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity_assets', '0006_comunityasset_poblacion_objetivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunityasset',
            name='contacto_info',
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='accesibilidad_silla_ruedas',
            field=models.BooleanField(default=False, verbose_name='Acceso para sillas de ruedas'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='accesibilidad_visual',
            field=models.BooleanField(default=False, verbose_name='Señalética Braille o sonora'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='baño_accesible',
            field=models.BooleanField(default=False, verbose_name='Cuenta con baño adaptado'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='contacto_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='contacto_fono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='estacionamiento_discapacidad',
            field=models.BooleanField(default=False, verbose_name='Estacionamiento preferencial para discapacidad'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='estacionamiento_general',
            field=models.BooleanField(default=False, verbose_name='Cuenta con estacionamiento'),
        ),
        migrations.AddField(
            model_name='comunityasset',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comunityasset',
            name='requiere_inscripcion',
            field=models.BooleanField(default=False),
        ),
    ]
