# Generated by Django 5.2.11 on 2026-02-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunity_assets', '0007_remove_comunityasset_contacto_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunityasset',
            name='categoria_mais',
            field=models.CharField(blank=True, choices=[('estres', 'Reducir Estrés'), ('deporte', 'Hacer Deporte'), ('social', 'Apoyo Social'), ('taller', 'Talleres')], max_length=50, null=True),
        ),
    ]
